let list = [
	{
		text:"是否使用台灯/放在左前方/台灯是否过亮或过暗",
		index:1,
		field_Name:"is_desk_lamp",
		value:""
	},
	{
		text:"是否看书写字习惯歪头/握笔太低？距离是否适合?",
		index:2,
		field_Name:"is_habit",
		value:""
	},
	{
		text:"是否长时间玩电子产品/看电视/练琴/看书？",
		index:3,
		field_Name:"is_long_time_play",
		value:""
	},
	{
		text:"是否有佩戴眼镜/ok镜?",
		index:4,
		field_Name:"is_eyeglass",
		value:""
	},
	{
		text:"是否有使用散瞳剂/阿托品眼药水/长期服用药物等?",
		index:5,
		field_Name:"is_use_eyedrop",
		value:""
	},
	{
		text:"是否有身体状况？（鼻炎/抵抗力差）",
		index:6,
		field_Name:"is_health",
		value:""
	},
	{
		text:"是否有眼部情况？（发炎/受伤/手术）",
		index:7,
		field_Name:"is_op",
		value:""
	},
	{
		text:"是否有开夜灯入睡？",
		index:8,
		field_Name:"is_open_light_sleep",
		value:""
	},
	{
		text:"是否经常睡眠不足/失眠？",
		index:9,
		field_Name:"is_lose_sleep",
		value:""
	},
	{
		text:"是否挑食？/爱吃甜食/碳酸？",
		index:10,
		field_Name:"is_picky_eaters",
		value:""
	},
	{
		text:"是否使用其他视力辅助仪器或尝试其他视力矫正？",
		index:11,
		field_Name:"is_correct",
		value:""
	},
	{
		text:"是否上过多辅导课程？",
		index:12,
		field_Name:"is_lesson",
		value:""
	},
	{
		text:"是否住校/家长无法监督辅导？",
		index:13,
		field_Name:"is_resdenc",
		value:""
	},
	{
		text:"是否比较情绪化/不容易配合？",
		index:14,
		field_Name:"is_emo",
		value:""
	},
	{
		text:"是否自愿来训练/有决心坚持每天来训练？",
		index:15,
		field_Name:"is_voluntart",
		value:""
	},
	{
		text:"是否能每天利用15-30分钟做眼球训练/固定时间何时？",
		index:16,
		field_Name:"is_keep",
		value:""
	},
	{
		text:"是否清楚同意恢复的是裸视，电脑度数是无法改变的？",
		index:17,
		field_Name:"is_know",
		value:""
	},
]
export default list